<?php
/**
 *	Plug & Protect
 *
 *	-> Sterckx Jens
 *	-> Moinil Wesley
 *	-> Dauwe Jelle
 *
 *
 *
 *	File: Will generate an updated ProxyPass list for Apache2 mod_proxy
**/

//Set execution dir to the current file one
chdir(realpath(dirname(__FILE__)));

//Gather module information
$MySQLHost = "cluster.plugandprotect.eu";
$MySQLUser = "proxyset";
$MySQLPW = "User-123";
$DataBase = "plugandprotect";

// Create connection
$MySQL = new mysqli($MySQLHost, $MySQLUser, $MySQLPW, $DataBase);

// Check connection
if ($MySQL->connect_error) {
    die("Connection failed: " . $MySQL->connect_error);
}

$Query = "SELECT MAC, IP FROM tbl_modules;";

$result = $MySQL->query($Query);

if ($result->num_rows > 0)
{
	//Collect all the info
	$MAC_IP_ARRAY = array();
	while($row = $result->fetch_assoc()) 
	{
		$MAC_IP_ARRAY[] = $row;
    }
	
	
	//Generate the HTTP proxy set.
	$proxy_string = "\t#CAMERA PROXY'S GENERATED BY /root/generateProxys.php\n";
	foreach($MAC_IP_ARRAY as $MIS)
	{
		$MAC = $MIS['MAC'];
		$IP = $MIS['IP'];
		$proxy_string .= "\tProxyPass /$MAC http://$IP:1027/\n";
	}
	$proxy_string .= "\t#DONE";
	//Get templates
	$http = file_get_contents("template.http");
	if($http != false)
	{
		$http = str_replace("{PROXY}", $proxy_string, $http);
	}
	$https = file_get_contents("template.https");
	if($https != false)
	{
		$https = str_replace("{PROXY}", $proxy_string, $https);
	}
	
	//Write new content to files
	file_put_contents("/etc/apache2/sites-enabled/000-default.conf", $http);
	file_put_contents("/etc/apache2/sites-enabled/default-ssl.conf", $https);
	
	//Converting from Windows format to Linux format
	//exec("dos2unix /etc/apache2/sites-enabled/000-default.conf");
	//exec("dos2unix /etc/apache2/sites-enabled/default-ssl.conf");
	//Not needed
	
	//Reload apache's new proxy's
	exec("service apache2 reload");
	
	//done
}
else
{
	//No hosts to add, so do nothing
	//echo "no";
}

/** Closing the MySQL connection **/
$MySQL->close();
?>