-- phpMyAdmin SQL Dump
-- version 3.4.11.1deb2+deb7u1
-- http://www.phpmyadmin.net
--
-- Machine: localhost
-- Genereertijd: 25 apr 2015 om 20:45
-- Serverversie: 5.5.41
-- PHP-Versie: 5.4.36-0+deb7u3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Databank: `plugandprotect`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `tbl_logs`
--

CREATE TABLE IF NOT EXISTS `tbl_logs` (
  `log_id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(128) NOT NULL,
  `IP` varchar(15) NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  UNIQUE KEY `date` (`date`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=31 ;

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `tbl_mconfig`
--

CREATE TABLE IF NOT EXISTS `tbl_mconfig` (
  `MAC` varchar(17) NOT NULL,
  `type` varchar(45) NOT NULL,
  `file` varchar(512) NOT NULL,
  `content` text NOT NULL,
  PRIMARY KEY (`MAC`,`file`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Gegevens worden uitgevoerd voor tabel `tbl_mconfig`
--

INSERT INTO `tbl_mconfig` (`MAC`, `type`, `file`, `content`) VALUES
('b8:27:eb:0f:05:c4', 'CAMERA', '/etc/motion/motion.conf', '# Rename this distribution example file to motion.conf\r\n#\r\n# This config file was generated by motion 3.2.12\r\n\r\n\r\n############################################################\r\n# Daemon\r\n############################################################\r\n\r\n# Start in daemon (background) mode and release terminal (default: off)\r\ndaemon off\r\n\r\n# File to store the process ID, also called pid file. (default: not defined)\r\nprocess_id_file /var/run/motion/motion.pid \r\n\r\n############################################################\r\n# Basic Setup Mode\r\n############################################################\r\n\r\n# Start in Setup-Mode, daemon disabled. (default: off)\r\nsetup_mode off\r\n\r\n###########################################################\r\n# Capture device options\r\n############################################################\r\n\r\n# Videodevice to be used for capturing  (default /dev/video0)\r\n# for FreeBSD default is /dev/bktr0\r\nvideodevice /dev/video0\r\n\r\n# v4l2_palette allows to choose preferable palette to be use by motion\r\n# to capture from those supported by your videodevice. (default: 8)\r\n# E.g. if your videodevice supports both V4L2_PIX_FMT_SBGGR8 and\r\n# V4L2_PIX_FMT_MJPEG then motion will by default use V4L2_PIX_FMT_MJPEG.\r\n# Setting v4l2_palette to 1 forces motion to use V4L2_PIX_FMT_SBGGR8\r\n# instead.\r\n#\r\n# Values :\r\n# V4L2_PIX_FMT_SN9C10X : 0  ''S910''\r\n# V4L2_PIX_FMT_SBGGR8  : 1  ''BA81''\r\n# V4L2_PIX_FMT_MJPEG   : 2  ''MJPEG''\r\n# V4L2_PIX_FMT_JPEG    : 3  ''JPEG''\r\n# V4L2_PIX_FMT_RGB24   : 4  ''RGB3''\r\n# V4L2_PIX_FMT_UYVY    : 5  ''UYVY''\r\n# V4L2_PIX_FMT_YUYV    : 6  ''YUYV''\r\n# V4L2_PIX_FMT_YUV422P : 7  ''422P''\r\n# V4L2_PIX_FMT_YUV420  : 8  ''YU12''\r\nv4l2_palette 8\r\n\r\n# Tuner device to be used for capturing using tuner as source (default /dev/tuner0)\r\n# This is ONLY used for FreeBSD. Leave it commented out for Linux\r\n; tunerdevice /dev/tuner0\r\n\r\n# The video input to be used (default: 8)\r\n# Should normally be set to 0 or 1 for video/TV cards, and 8 for USB cameras\r\ninput 8\r\n\r\n# The video norm to use (only for video capture and TV tuner cards)\r\n# Values: 0 (PAL), 1 (NTSC), 2 (SECAM), 3 (PAL NC no colour). Default: 0 (PAL)\r\nnorm 0\r\n\r\n# The frequency to set the tuner to (kHz) (only for TV tuner cards) (default: 0)\r\nfrequency 0\r\n\r\n# Rotate image this number of degrees. The rotation affects all saved images as\r\n# well as mpeg movies. Valid values: 0 (default = no rotation), 90, 180 and 270.\r\nrotate 0\r\n\r\n# Image width (pixels). Valid range: Camera dependent, default: 352\r\nwidth 640\r\n\r\n# Image height (pixels). Valid range: Camera dependent, default: 288\r\nheight 480\r\n\r\n# Maximum number of frames to be captured per second.\r\n# Valid range: 2-100. Default: 100 (almost no limit).\r\nframerate 100\r\n\r\n# Minimum time in seconds between capturing picture frames from the camera.\r\n# Default: 0 = disabled - the capture rate is given by the camera framerate.\r\n# This option is used when you want to capture images at a rate lower than 2 per second.\r\nminimum_frame_time 0\r\n\r\n# URL to use if you are using a network camera, size will be autodetected (incl http:// ftp:// or file:///)\r\n# Must be a URL that returns single jpeg pictures or a raw mjpeg stream. Default: Not defined\r\n; netcam_url value\r\n\r\n# Username and password for network camera (only if required). Default: not defined\r\n# Syntax is user:password\r\n; netcam_userpass value\r\n\r\n# The setting for keep-alive of network socket, should improve performance on compatible net cameras.\r\n# 1.0:         The historical implementation using HTTP/1.0, closing the socket after each http request.\r\n# keep_alive:  Use HTTP/1.0 requests with keep alive header to reuse the same connection.\r\n# 1.1:         Use HTTP/1.1 requests that support keep alive as default.\r\n# Default: 1.0\r\n; netcam_http 1.0\r\n\r\n# URL to use for a netcam proxy server, if required, e.g. "http://myproxy".\r\n# If a port number other than 80 is needed, use "http://myproxy:1234".\r\n# Default: not defined\r\n; netcam_proxy value \r\n\r\n# Set less strict jpeg checks for network cameras with a poor/buggy firmware.\r\n# Default: off\r\nnetcam_tolerant_check off\r\n\r\n# Let motion regulate the brightness of a video device (default: off).\r\n# The auto_brightness feature uses the brightness option as its target value.\r\n# If brightness is zero auto_brightness will adjust to average brightness value 128.\r\n# Only recommended for cameras without auto brightness\r\nauto_brightness off\r\n\r\n# Set the initial brightness of a video device.\r\n# If auto_brightness is enabled, this value defines the average brightness level\r\n# which Motion will try and adjust to.\r\n# Valid range 0-255, default 0 = disabled\r\nbrightness 0\r\n\r\n# Set the contrast of a video device.\r\n# Valid range 0-255, default 0 = disabled\r\ncontrast 0\r\n\r\n# Set the saturation of a video device.\r\n# Valid range 0-255, default 0 = disabled\r\nsaturation 0\r\n\r\n# Set the hue of a video device (NTSC feature).\r\n# Valid range 0-255, default 0 = disabled\r\nhue 0\r\n\r\n\r\n############################################################\r\n# Round Robin (multiple inputs on same video device name)\r\n############################################################\r\n\r\n# Number of frames to capture in each roundrobin step (default: 1)\r\nroundrobin_frames 1\r\n\r\n# Number of frames to skip before each roundrobin step (default: 1)\r\nroundrobin_skip 1\r\n\r\n# Try to filter out noise generated by roundrobin (default: off)\r\nswitchfilter off\r\n\r\n\r\n############################################################\r\n# Motion Detection Settings:\r\n############################################################\r\n\r\n# Threshold for number of changed pixels in an image that\r\n# triggers motion detection (default: 1500)\r\nthreshold 1500\r\n\r\n# Automatically tune the threshold down if possible (default: off)\r\nthreshold_tune off\r\n\r\n# Noise threshold for the motion detection (default: 32)\r\nnoise_level 32\r\n\r\n# Automatically tune the noise threshold (default: on)\r\nnoise_tune on\r\n\r\n# Despeckle motion image using (e)rode or (d)ilate or (l)abel (Default: not defined)\r\n# Recommended value is EedDl. Any combination (and number of) of E, e, d, and D is valid.\r\n# (l)abeling must only be used once and the ''l'' must be the last letter.\r\n# Comment out to disable\r\ndespeckle EedDl\r\n\r\n# Detect motion in predefined areas (1 - 9). Areas are numbered like that:  1 2 3\r\n# A script (on_area_detected) is started immediately when motion is         4 5 6\r\n# detected in one of the given areas, but only once during an event.        7 8 9\r\n# One or more areas can be specified with this option. (Default: not defined)\r\n; area_detect value\r\n\r\n# PGM file to use as a sensitivity mask.\r\n# Full path name to. (Default: not defined)\r\n; mask_file value\r\n\r\n# Dynamically create a mask file during operation (default: 0)\r\n# Adjust speed of mask changes from 0 (off) to 10 (fast)\r\nsmart_mask_speed 0\r\n\r\n# Ignore sudden massive light intensity changes given as a percentage of the picture\r\n# area that changed intensity. Valid range: 0 - 100 , default: 0 = disabled\r\nlightswitch 0\r\n\r\n# Picture frames must contain motion at least the specified number of frames\r\n# in a row before they are detected as true motion. At the default of 1, all\r\n# motion is detected. Valid range: 1 to thousands, recommended 1-5\r\nminimum_motion_frames 1\r\n\r\n# Specifies the number of pre-captured (buffered) pictures from before motion\r\n# was detected that will be output at motion detection.\r\n# Recommended range: 0 to 5 (default: 0)\r\n# Do not use large values! Large values will cause Motion to skip video frames and\r\n# cause unsmooth mpegs. To smooth mpegs use larger values of post_capture instead.\r\npre_capture 0\r\n\r\n# Number of frames to capture after motion is no longer detected (default: 0)\r\npost_capture 0\r\n\r\n# Gap is the seconds of no motion detection that triggers the end of an event\r\n# An event is defined as a series of motion images taken within a short timeframe.\r\n# Recommended value is 60 seconds (Default). The value 0 is allowed and disables\r\n# events causing all Motion to be written to one single mpeg file and no pre_capture.\r\ngap 60\r\n\r\n# Maximum length in seconds of an mpeg movie\r\n# When value is exceeded a new mpeg file is created. (Default: 0 = infinite)\r\nmax_mpeg_time 0\r\n\r\n# Always save images even if there was no motion (default: off)\r\noutput_all off\r\n\r\n\r\n############################################################\r\n# Image File Output\r\n############################################################\r\n\r\n# Output ''normal'' pictures when motion is detected (default: on)\r\n# Valid values: on, off, first, best, center\r\n# When set to ''first'', only the first picture of an event is saved.\r\n# Picture with most motion of an event is saved when set to ''best''.\r\n# Picture with motion nearest center of picture is saved when set to ''center''.\r\n# Can be used as preview shot for the corresponding movie.\r\noutput_normal on\r\n\r\n# Output pictures with only the pixels moving object (ghost images) (default: off)\r\noutput_motion off\r\n\r\n# The quality (in percent) to be used by the jpeg compression (default: 75)\r\nquality 100\r\n\r\n# Output ppm images instead of jpeg (default: off)\r\nppm off\r\n\r\n\r\n############################################################\r\n# FFMPEG related options\r\n# Film (mpeg) file output, and deinterlacing of the video input\r\n# The options movie_filename and timelapse_filename are also used\r\n# by the ffmpeg feature\r\n############################################################\r\n\r\n# Use ffmpeg to encode mpeg movies in realtime (default: off)\r\nffmpeg_cap_new on\r\n\r\n# Use ffmpeg to make movies with only the pixels moving\r\n# object (ghost images) (default: off)\r\nffmpeg_cap_motion off\r\n\r\n# Use ffmpeg to encode a timelapse movie \r\n# Default value 0 = off - else save frame every Nth second\r\nffmpeg_timelapse 0\r\n\r\n# The file rollover mode of the timelapse video\r\n# Valid values: hourly, daily (default), weekly-sunday, weekly-monday, monthly, manual\r\nffmpeg_timelapse_mode daily\r\n\r\n# Bitrate to be used by the ffmpeg encoder (default: 400000)\r\n# This option is ignored if ffmpeg_variable_bitrate is not 0 (disabled)\r\nffmpeg_bps 400000\r\n\r\n# Enables and defines variable bitrate for the ffmpeg encoder.\r\n# ffmpeg_bps is ignored if variable bitrate is enabled.\r\n# Valid values: 0 (default) = fixed bitrate defined by ffmpeg_bps,\r\n# or the range 2 - 31 where 2 means best quality and 31 is worst.\r\nffmpeg_variable_bitrate 0\r\n\r\n# Codec to used by ffmpeg for the video compression.\r\n# Timelapse mpegs are always made in mpeg1 format independent from this option.\r\n# Supported formats are: mpeg1 (ffmpeg-0.4.8 only), mpeg4 (default), and msmpeg4.\r\n# mpeg1 - gives you files with extension .mpg\r\n# mpeg4 or msmpeg4 - gives you files with extension .avi\r\n# msmpeg4 is recommended for use with Windows Media Player because\r\n# it requires no installation of codec on the Windows client.\r\n# swf - gives you a flash film with extension .swf\r\n# flv - gives you a flash video with extension .flv\r\n# ffv1 - FF video codec 1 for Lossless Encoding ( experimental )\r\n# mov - QuickTime ( testing )\r\nffmpeg_video_codec msmpeg4\r\n\r\n# Use ffmpeg to deinterlace video. Necessary if you use an analog camera\r\n# and see horizontal combing on moving objects in video or pictures.\r\n# (default: off)\r\nffmpeg_deinterlace off\r\n\r\n\r\n############################################################\r\n# Snapshots (Traditional Periodic Webcam File Output)\r\n############################################################\r\n\r\n# Make automated snapshot every N seconds (default: 0 = disabled)\r\nsnapshot_interval 0\r\n\r\n\r\n############################################################\r\n# Text Display\r\n# %Y = year, %m = month, %d = date,\r\n# %H = hour, %M = minute, %S = second, %T = HH:MM:SS,\r\n# %v = event, %q = frame number, %t = thread (camera) number,\r\n# %D = changed pixels, %N = noise level, \\n = new line,\r\n# %i and %J = width and height of motion area,\r\n# %K and %L = X and Y coordinates of motion center\r\n# %C = value defined by text_event - do not use with text_event!\r\n# You can put quotation marks around the text to allow\r\n# leading spaces\r\n############################################################\r\n\r\n# Locate and draw a box around the moving object.\r\n# Valid values: on, off and preview (default: off)\r\n# Set to ''preview'' will only draw a box in preview_shot pictures.\r\nlocate on\r\n\r\n# Draws the timestamp using same options as C function strftime(3)\r\n# Default: %Y-%m-%d\\n%T = date in ISO format and time in 24 hour clock\r\n# Text is placed in lower right corner\r\ntext_right %Y-%m-%d\\n%T-%q\r\n\r\n# Draw a user defined text on the images using same options as C function strftime(3)\r\n# Default: Not defined = no text\r\n# Text is placed in lower left corner\r\n; text_left CAMERA %t\r\n\r\n# Draw the number of changed pixed on the images (default: off)\r\n# Will normally be set to off except when you setup and adjust the motion settings\r\n# Text is placed in upper right corner\r\ntext_changes off\r\n\r\n# This option defines the value of the special event conversion specifier %C\r\n# You can use any conversion specifier in this option except %C. Date and time\r\n# values are from the timestamp of the first image in the current event.\r\n# Default: %Y%m%d%H%M%S\r\n# The idea is that %C can be used filenames and text_left/right for creating\r\n# a unique identifier for each event.\r\ntext_event %Y%m%d%H%M%S\r\n\r\n# Draw characters at twice normal size on images. (default: off)\r\ntext_double off\r\n\r\n\r\n############################################################\r\n# Target Directories and filenames For Images And Films\r\n# For the options snapshot_, jpeg_, mpeg_ and timelapse_filename\r\n# you can use conversion specifiers\r\n# %Y = year, %m = month, %d = date,\r\n# %H = hour, %M = minute, %S = second,\r\n# %v = event, %q = frame number, %t = thread (camera) number,\r\n# %D = changed pixels, %N = noise level,\r\n# %i and %J = width and height of motion area,\r\n# %K and %L = X and Y coordinates of motion center\r\n# %C = value defined by text_event\r\n# Quotation marks round string are allowed.\r\n############################################################\r\n\r\n# Target base directory for pictures and films\r\n# Recommended to use absolute path. (Default: current working directory)\r\ntarget_dir /mnt/nfscontrol/node1/motion\r\n\r\n# File path for snapshots (jpeg or ppm) relative to target_dir\r\n# Default: %v-%Y%m%d%H%M%S-snapshot\r\n# Default value is equivalent to legacy oldlayout option\r\n# For Motion 3.0 compatible mode choose: %Y/%m/%d/%H/%M/%S-snapshot\r\n# File extension .jpg or .ppm is automatically added so do not include this.\r\n# Note: A symbolic link called lastsnap.jpg created in the target_dir will always\r\n# point to the latest snapshot, unless snapshot_filename is exactly ''lastsnap''\r\nsnapshot_filename %v-%Y%m%d%H%M%S-snapshot\r\n\r\n# File path for motion triggered images (jpeg or ppm) relative to target_dir\r\n# Default: %v-%Y%m%d%H%M%S-%q\r\n# Default value is equivalent to legacy oldlayout option\r\n# For Motion 3.0 compatible mode choose: %Y/%m/%d/%H/%M/%S-%q\r\n# File extension .jpg or .ppm is automatically added so do not include this\r\n# Set to ''preview'' together with best-preview feature enables special naming\r\n# convention for preview shots. See motion guide for details\r\njpeg_filename %v-%Y%m%d%H%M%S-%q\r\n\r\n# File path for motion triggered ffmpeg films (mpeg) relative to target_dir\r\n# Default: %v-%Y%m%d%H%M%S\r\n# Default value is equivalent to legacy oldlayout option\r\n# For Motion 3.0 compatible mode choose: %Y/%m/%d/%H%M%S\r\n# File extension .mpg or .avi is automatically added so do not include this\r\n# This option was previously called ffmpeg_filename\r\nmovie_filename %v-%Y%m%d%H%M%S\r\n\r\n# File path for timelapse mpegs relative to target_dir\r\n# Default: %Y%m%d-timelapse\r\n# Default value is near equivalent to legacy oldlayout option\r\n# For Motion 3.0 compatible mode choose: %Y/%m/%d-timelapse\r\n# File extension .mpg is automatically added so do not include this\r\ntimelapse_filename %Y%m%d-timelapse\r\n\r\n\r\n############################################################\r\n# Live Webcam Server\r\n############################################################\r\n\r\n# The mini-http server listens to this port for requests (default: 0 = disabled)\r\nwebcam_port 1026\r\n\r\n# Quality of the jpeg (in percent) images produced (default: 50) \r\nwebcam_quality 60\r\n\r\n# Output frames at 1 fps when no motion is detected and increase to the\r\n# rate given by webcam_maxrate when motion is detected (default: off)\r\nwebcam_motion off\r\n\r\n# Maximum framerate for webcam streams (default: 1)\r\nwebcam_maxrate 30\r\n\r\n# Restrict webcam connections to localhost only (default: on)\r\nwebcam_localhost off\r\n\r\n# Limits the number of images per connection (default: 0 = unlimited)\r\n# Number can be defined by multiplying actual webcam rate by desired number of seconds\r\n# Actual webcam rate is the smallest of the numbers framerate and webcam_maxrate\r\nwebcam_limit 0\r\n\r\n\r\n############################################################\r\n# HTTP Based Control\r\n############################################################\r\n\r\n# TCP/IP port for the http server to listen on (default: 0 = disabled)\r\ncontrol_port 8080\r\n\r\n# Restrict control connections to localhost only (default: on)\r\ncontrol_localhost off\r\n\r\n# Output for http server, select off to choose raw text plain (default: on)\r\ncontrol_html_output on\r\n\r\n# Authentication for the http based control. Syntax username:password\r\n# Default: not defined (Disabled)\r\n; control_authentication username:password\r\n\r\n\r\n############################################################\r\n# Tracking (Pan/Tilt)\r\n############################################################\r\n\r\n# Type of tracker (0=none (default), 1=stepper, 2=iomojo, 3=pwc, 4=generic, 5=uvcvideo)\r\n# The generic type enables the definition of motion center and motion size to\r\n# be used with the conversion specifiers for options like on_motion_detected\r\ntrack_type 0\r\n\r\n# Enable auto tracking (default: off)\r\ntrack_auto off\r\n\r\n# Serial port of motor (default: none)\r\n; track_port value\r\n\r\n# Motor number for x-axis (default: 0)\r\ntrack_motorx 0\r\n\r\n# Motor number for y-axis (default: 0)\r\ntrack_motory 0\r\n\r\n# Maximum value on x-axis (default: 0)\r\ntrack_maxx 0\r\n\r\n# Maximum value on y-axis (default: 0)\r\ntrack_maxy 0\r\n\r\n# ID of an iomojo camera if used (default: 0)\r\ntrack_iomojo_id 0\r\n\r\n# Angle in degrees the camera moves per step on the X-axis\r\n# with auto-track (default: 10)\r\n# Currently only used with pwc type cameras\r\ntrack_step_angle_x 10\r\n\r\n# Angle in degrees the camera moves per step on the Y-axis\r\n# with auto-track (default: 10)\r\n# Currently only used with pwc type cameras\r\ntrack_step_angle_y 10\r\n\r\n# Delay to wait for after tracking movement as number\r\n# of picture frames (default: 10)\r\ntrack_move_wait 10\r\n\r\n# Speed to set the motor to (stepper motor option) (default: 255)\r\ntrack_speed 255\r\n\r\n# Number of steps to make (stepper motor option) (default: 40)\r\ntrack_stepsize 40\r\n\r\n\r\n############################################################\r\n# External Commands, Warnings and Logging:\r\n# You can use conversion specifiers for the on_xxxx commands\r\n# %Y = year, %m = month, %d = date,\r\n# %H = hour, %M = minute, %S = second,\r\n# %v = event, %q = frame number, %t = thread (camera) number,\r\n# %D = changed pixels, %N = noise level,\r\n# %i and %J = width and height of motion area,\r\n# %K and %L = X and Y coordinates of motion center\r\n# %C = value defined by text_event\r\n# %f = filename with full path\r\n# %n = number indicating filetype\r\n# Both %f and %n are only defined for on_picture_save,\r\n# on_movie_start and on_movie_end\r\n# Quotation marks round string are allowed.\r\n############################################################\r\n\r\n# Do not sound beeps when detecting motion (default: on)\r\n# Note: Motion never beeps when running in daemon mode.\r\nquiet on\r\n\r\n# Command to be executed when an event starts. (default: none)\r\n# An event starts at first motion detected after a period of no motion defined by gap \r\n; on_event_start value\r\n\r\n# Command to be executed when an event ends after a period of no motion\r\n# (default: none). The period of no motion is defined by option gap.\r\n; on_event_end value\r\n\r\n# Command to be executed when a picture (.ppm|.jpg) is saved (default: none)\r\n# To give the filename as an argument to a command append it with %f\r\n; on_picture_save value\r\n\r\n# Command to be executed when a motion frame is detected (default: none)\r\n; on_motion_detected value\r\n\r\n# Command to be executed when motion in a predefined area is detected\r\n# Check option ''area_detect''.   (default: none)\r\n; on_area_detected value\r\n\r\n# Command to be executed when a movie file (.mpg|.avi) is created. (default: none)\r\n# To give the filename as an argument to a command append it with %f\r\n; on_movie_start value\r\n\r\n# Command to be executed when a movie file (.mpg|.avi) is closed. (default: none)\r\n# To give the filename as an argument to a command append it with %f\r\n; on_movie_end value\r\n\r\n# Command to be executed when a camera can''t be opened or if it is lost\r\n# NOTE: There is situations when motion doesn''t detect a lost camera!\r\n# It depends on the driver, some drivers don''t detect a lost camera at all\r\n# Some hang the motion thread. Some even hang the PC! (default: none)\r\n; on_camera_lost value\r\n\r\n############################################################\r\n# Common Options For MySQL and PostgreSQL database features.\r\n# Options require the MySQL/PostgreSQL options to be active also.\r\n############################################################\r\n\r\n# Log to the database when creating motion triggered image file  (default: on)\r\nsql_log_image on\r\n\r\n# Log to the database when creating a snapshot image file (default: on)\r\nsql_log_snapshot on\r\n\r\n# Log to the database when creating motion triggered mpeg file (default: off)\r\nsql_log_mpeg off\r\n\r\n# Log to the database when creating timelapse mpeg file (default: off)\r\nsql_log_timelapse off\r\n\r\n# SQL query string that is sent to the database\r\n# Use same conversion specifiers has for text features\r\n# Additional special conversion specifiers are\r\n# %n = the number representing the file_type\r\n# %f = filename with full path\r\n# Default value:\r\n# insert into security(camera, filename, frame, file_type, time_stamp, text_event) values(''%t'', ''%f'', ''%q'', ''%n'', ''%Y-%m-%d %T'', ''%C'')\r\nsql_query insert into security(camera, filename, frame, file_type, time_stamp, event_time_stamp) values(''%t'', ''%f'', ''%q'', ''%n'', ''%Y-%m-%d %T'', ''%C'')\r\n\r\n\r\n############################################################\r\n# Database Options For MySQL\r\n############################################################\r\n\r\n# Mysql database to log to (default: not defined)\r\n; mysql_db value\r\n\r\n# The host on which the database is located (default: localhost)\r\n; mysql_host value\r\n\r\n# User account name for MySQL database (default: not defined)\r\n; mysql_user value\r\n\r\n# User password for MySQL database (default: not defined)\r\n; mysql_password value\r\n\r\n\r\n############################################################\r\n# Database Options For PostgreSQL\r\n############################################################\r\n\r\n# PostgreSQL database to log to (default: not defined)\r\n; pgsql_db value\r\n\r\n# The host on which the database is located (default: localhost)\r\n; pgsql_host value\r\n\r\n# User account name for PostgreSQL database (default: not defined)\r\n; pgsql_user value\r\n\r\n# User password for PostgreSQL database (default: not defined)\r\n; pgsql_password value\r\n\r\n# Port on which the PostgreSQL database is located (default: 5432)\r\n; pgsql_port 5432\r\n\r\n\r\n############################################################\r\n# Video Loopback Device (vloopback project)\r\n############################################################\r\n\r\n# Output images to a video4linux loopback device\r\n# The value ''-'' means next available (default: not defined)\r\n; video_pipe value\r\n\r\n# Output motion images to a video4linux loopback device\r\n# The value ''-'' means next available (default: not defined)\r\n; motion_video_pipe value\r\n\r\n\r\n##############################################################\r\n# Thread config files - One for each camera.\r\n# Except if only one camera - You only need this config file.\r\n# If you have more than one camera you MUST define one thread\r\n# config file for each camera in addition to this config file.\r\n##############################################################\r\n\r\n# Remember: If you have more than one camera you must have one\r\n# thread file for each camera. E.g. 2 cameras requires 3 files:\r\n# This motion.conf file AND thread1.conf and thread2.conf.\r\n# Only put the options that are unique to each camera in the\r\n# thread config files. \r\n; thread /usr/local/etc/thread1.conf\r\n; thread /usr/local/etc/thread2.conf\r\n; thread /usr/local/etc/thread3.conf\r\n; thread /usr/local/etc/thread4.conf\r\n\r\n'),
('b8:27:eb:0f:05:c4', 'GENERAL', '/root/files/jens/complete.config', 'start'),
('b8:27:eb:0f:05:c4', 'STORAGE', '/root/fstabtest', 'sdsd ** * *sdfs d*fdsg*'),
('b8:27:eb:0f:05:c4', 'CAMERA', '/root/test', 'This is a test fileee.');
INSERT INTO `tbl_mconfig` (`MAC`, `type`, `file`, `content`) VALUES
('b8:27:eb:d5:dc:f0', 'CAMERA', '/etc/motion/motion.conf', '# Rename this distribution example file to motion.conf\r\n#\r\n# This config file was generated by motion 3.2.12\r\n\r\n\r\n############################################################\r\n# Daemon\r\n############################################################\r\n\r\n# Start in daemon (background) mode and release terminal (default: off)\r\ndaemon on\r\n\r\n# File to store the process ID, also called pid file. (default: not defined)\r\n#process_id_file /var/run/motion/motion.pid \r\n\r\n############################################################\r\n# Basic Setup Mode\r\n############################################################\r\n\r\n# Start in Setup-Mode, daemon disabled. (default: off)\r\nsetup_mode off\r\n\r\n###########################################################\r\n# Capture device options\r\n############################################################\r\n\r\n# Videodevice to be used for capturing  (default /dev/video0)\r\n# for FreeBSD default is /dev/bktr0\r\nvideodevice /dev/video0\r\n\r\n# v4l2_palette allows to choose preferable palette to be use by motion\r\n# to capture from those supported by your videodevice. (default: 8)\r\n# E.g. if your videodevice supports both V4L2_PIX_FMT_SBGGR8 and\r\n# V4L2_PIX_FMT_MJPEG then motion will by default use V4L2_PIX_FMT_MJPEG.\r\n# Setting v4l2_palette to 1 forces motion to use V4L2_PIX_FMT_SBGGR8\r\n# instead.\r\n#\r\n# Values :\r\n# V4L2_PIX_FMT_SN9C10X : 0  ''S910''\r\n# V4L2_PIX_FMT_SBGGR8  : 1  ''BA81''\r\n# V4L2_PIX_FMT_MJPEG   : 2  ''MJPEG''\r\n# V4L2_PIX_FMT_JPEG    : 3  ''JPEG''\r\n# V4L2_PIX_FMT_RGB24   : 4  ''RGB3''\r\n# V4L2_PIX_FMT_UYVY    : 5  ''UYVY''\r\n# V4L2_PIX_FMT_YUYV    : 6  ''YUYV''\r\n# V4L2_PIX_FMT_YUV422P : 7  ''422P''\r\n# V4L2_PIX_FMT_YUV420  : 8  ''YU12''\r\nv4l2_palette 8\r\n\r\n# Tuner device to be used for capturing using tuner as source (default /dev/tuner0)\r\n# This is ONLY used for FreeBSD. Leave it commented out for Linux\r\n; tunerdevice /dev/tuner0\r\n\r\n# The video input to be used (default: 8)\r\n# Should normally be set to 0 or 1 for video/TV cards, and 8 for USB cameras\r\ninput 8\r\n\r\n# The video norm to use (only for video capture and TV tuner cards)\r\n# Values: 0 (PAL), 1 (NTSC), 2 (SECAM), 3 (PAL NC no colour). Default: 0 (PAL)\r\nnorm 0\r\n\r\n# The frequency to set the tuner to (kHz) (only for TV tuner cards) (default: 0)\r\nfrequency 0\r\n\r\n# Rotate image this number of degrees. The rotation affects all saved images as\r\n# well as mpeg movies. Valid values: 0 (default = no rotation), 90, 180 and 270.\r\nrotate 0\r\n\r\n# Image width (pixels). Valid range: Camera dependent, default: 352\r\nwidth 640\r\n\r\n# Image height (pixels). Valid range: Camera dependent, default: 288\r\nheight 480\r\n\r\n# Maximum number of frames to be captured per second.\r\n# Valid range: 2-100. Default: 100 (almost no limit).\r\nframerate 100\r\n\r\n# Minimum time in seconds between capturing picture frames from the camera.\r\n# Default: 0 = disabled - the capture rate is given by the camera framerate.\r\n# This option is used when you want to capture images at a rate lower than 2 per second.\r\nminimum_frame_time 0\r\n\r\n# URL to use if you are using a network camera, size will be autodetected (incl http:// ftp:// or file:///)\r\n# Must be a URL that returns single jpeg pictures or a raw mjpeg stream. Default: Not defined\r\n; netcam_url value\r\n\r\n# Username and password for network camera (only if required). Default: not defined\r\n# Syntax is user:password\r\n; netcam_userpass value\r\n\r\n# The setting for keep-alive of network socket, should improve performance on compatible net cameras.\r\n# 1.0:         The historical implementation using HTTP/1.0, closing the socket after each http request.\r\n# keep_alive:  Use HTTP/1.0 requests with keep alive header to reuse the same connection.\r\n# 1.1:         Use HTTP/1.1 requests that support keep alive as default.\r\n# Default: 1.0\r\n; netcam_http 1.0\r\n\r\n# URL to use for a netcam proxy server, if required, e.g. "http://myproxy".\r\n# If a port number other than 80 is needed, use "http://myproxy:1234".\r\n# Default: not defined\r\n; netcam_proxy value \r\n\r\n# Set less strict jpeg checks for network cameras with a poor/buggy firmware.\r\n# Default: off\r\nnetcam_tolerant_check off\r\n\r\n# Let motion regulate the brightness of a video device (default: off).\r\n# The auto_brightness feature uses the brightness option as its target value.\r\n# If brightness is zero auto_brightness will adjust to average brightness value 128.\r\n# Only recommended for cameras without auto brightness\r\nauto_brightness off\r\n\r\n# Set the initial brightness of a video device.\r\n# If auto_brightness is enabled, this value defines the average brightness level\r\n# which Motion will try and adjust to.\r\n# Valid range 0-255, default 0 = disabled\r\nbrightness 0\r\n\r\n# Set the contrast of a video device.\r\n# Valid range 0-255, default 0 = disabled\r\ncontrast 0\r\n\r\n# Set the saturation of a video device.\r\n# Valid range 0-255, default 0 = disabled\r\nsaturation 0\r\n\r\n# Set the hue of a video device (NTSC feature).\r\n# Valid range 0-255, default 0 = disabled\r\nhue 0\r\n\r\n\r\n############################################################\r\n# Round Robin (multiple inputs on same video device name)\r\n############################################################\r\n\r\n# Number of frames to capture in each roundrobin step (default: 1)\r\nroundrobin_frames 1\r\n\r\n# Number of frames to skip before each roundrobin step (default: 1)\r\nroundrobin_skip 1\r\n\r\n# Try to filter out noise generated by roundrobin (default: off)\r\nswitchfilter off\r\n\r\n\r\n############################################################\r\n# Motion Detection Settings:\r\n############################################################\r\n\r\n# Threshold for number of changed pixels in an image that\r\n# triggers motion detection (default: 1500)\r\nthreshold 1500\r\n\r\n# Automatically tune the threshold down if possible (default: off)\r\nthreshold_tune off\r\n\r\n# Noise threshold for the motion detection (default: 32)\r\nnoise_level 32\r\n\r\n# Automatically tune the noise threshold (default: on)\r\nnoise_tune on\r\n\r\n# Despeckle motion image using (e)rode or (d)ilate or (l)abel (Default: not defined)\r\n# Recommended value is EedDl. Any combination (and number of) of E, e, d, and D is valid.\r\n# (l)abeling must only be used once and the ''l'' must be the last letter.\r\n# Comment out to disable\r\ndespeckle EedDl\r\n\r\n# Detect motion in predefined areas (1 - 9). Areas are numbered like that:  1 2 3\r\n# A script (on_area_detected) is started immediately when motion is         4 5 6\r\n# detected in one of the given areas, but only once during an event.        7 8 9\r\n# One or more areas can be specified with this option. (Default: not defined)\r\n; area_detect value\r\n\r\n# PGM file to use as a sensitivity mask.\r\n# Full path name to. (Default: not defined)\r\n; mask_file value\r\n\r\n# Dynamically create a mask file during operation (default: 0)\r\n# Adjust speed of mask changes from 0 (off) to 10 (fast)\r\nsmart_mask_speed 0\r\n\r\n# Ignore sudden massive light intensity changes given as a percentage of the picture\r\n# area that changed intensity. Valid range: 0 - 100 , default: 0 = disabled\r\nlightswitch 0\r\n\r\n# Picture frames must contain motion at least the specified number of frames\r\n# in a row before they are detected as true motion. At the default of 1, all\r\n# motion is detected. Valid range: 1 to thousands, recommended 1-5\r\nminimum_motion_frames 1\r\n\r\n# Specifies the number of pre-captured (buffered) pictures from before motion\r\n# was detected that will be output at motion detection.\r\n# Recommended range: 0 to 5 (default: 0)\r\n# Do not use large values! Large values will cause Motion to skip video frames and\r\n# cause unsmooth mpegs. To smooth mpegs use larger values of post_capture instead.\r\npre_capture 0\r\n\r\n# Number of frames to capture after motion is no longer detected (default: 0)\r\npost_capture 0\r\n\r\n# Gap is the seconds of no motion detection that triggers the end of an event\r\n# An event is defined as a series of motion images taken within a short timeframe.\r\n# Recommended value is 60 seconds (Default). The value 0 is allowed and disables\r\n# events causing all Motion to be written to one single mpeg file and no pre_capture.\r\ngap 60\r\n\r\n# Maximum length in seconds of an mpeg movie\r\n# When value is exceeded a new mpeg file is created. (Default: 0 = infinite)\r\nmax_mpeg_time 0\r\n\r\n# Always save images even if there was no motion (default: off)\r\noutput_all off\r\n\r\n\r\n############################################################\r\n# Image File Output\r\n############################################################\r\n\r\n# Output ''normal'' pictures when motion is detected (default: on)\r\n# Valid values: on, off, first, best, center\r\n# When set to ''first'', only the first picture of an event is saved.\r\n# Picture with most motion of an event is saved when set to ''best''.\r\n# Picture with motion nearest center of picture is saved when set to ''center''.\r\n# Can be used as preview shot for the corresponding movie.\r\n# EDIT\r\noutput_normal on\r\n\r\n# Output pictures with only the pixels moving object (ghost images) (default: off)\r\noutput_motion off\r\n\r\n# The quality (in percent) to be used by the jpeg compression (default: 75)\r\nquality 100\r\n\r\n# Output ppm images instead of jpeg (default: off)\r\nppm off\r\n\r\n\r\n############################################################\r\n# FFMPEG related options\r\n# Film (mpeg) file output, and deinterlacing of the video input\r\n# The options movie_filename and timelapse_filename are also used\r\n# by the ffmpeg feature\r\n############################################################\r\n\r\n# Use ffmpeg to encode mpeg movies in realtime (default: off)\r\nffmpeg_cap_new on\r\n\r\n# Use ffmpeg to make movies with only the pixels moving\r\n# object (ghost images) (default: off)\r\nffmpeg_cap_motion off\r\n\r\n# Use ffmpeg to encode a timelapse movie \r\n# Default value 0 = off - else save frame every Nth second\r\nffmpeg_timelapse 0\r\n\r\n# The file rollover mode of the timelapse video\r\n# Valid values: hourly, daily (default), weekly-sunday, weekly-monday, monthly, manual\r\nffmpeg_timelapse_mode daily\r\n\r\n# Bitrate to be used by the ffmpeg encoder (default: 400000)\r\n# This option is ignored if ffmpeg_variable_bitrate is not 0 (disabled)\r\nffmpeg_bps 400000\r\n\r\n# Enables and defines variable bitrate for the ffmpeg encoder.\r\n# ffmpeg_bps is ignored if variable bitrate is enabled.\r\n# Valid values: 0 (default) = fixed bitrate defined by ffmpeg_bps,\r\n# or the range 2 - 31 where 2 means best quality and 31 is worst.\r\nffmpeg_variable_bitrate 0\r\n\r\n# Codec to used by ffmpeg for the video compression.\r\n# Timelapse mpegs are always made in mpeg1 format independent from this option.\r\n# Supported formats are: mpeg1 (ffmpeg-0.4.8 only), mpeg4 (default), and msmpeg4.\r\n# mpeg1 - gives you files with extension .mpg\r\n# mpeg4 or msmpeg4 - gives you files with extension .avi\r\n# msmpeg4 is recommended for use with Windows Media Player because\r\n# it requires no installation of codec on the Windows client.\r\n# swf - gives you a flash film with extension .swf\r\n# flv - gives you a flash video with extension .flv\r\n# ffv1 - FF video codec 1 for Lossless Encoding ( experimental )\r\n# mov - QuickTime ( testing )\r\nffmpeg_video_codec msmpeg4\r\n#ffmpeg_video_codec swf\r\n\r\n# Use ffmpeg to deinterlace video. Necessary if you use an analog camera\r\n# and see horizontal combing on moving objects in video or pictures.\r\n# (default: off)\r\nffmpeg_deinterlace off\r\n\r\n\r\n############################################################\r\n# Snapshots (Traditional Periodic Webcam File Output)\r\n############################################################\r\n\r\n# Make automated snapshot every N seconds (default: 0 = disabled)\r\nsnapshot_interval 0\r\n\r\n\r\n############################################################\r\n# Text Display\r\n# %Y = year, %m = month, %d = date,\r\n# %H = hour, %M = minute, %S = second, %T = HH:MM:SS,\r\n# %v = event, %q = frame number, %t = thread (camera) number,\r\n# %D = changed pixels, %N = noise level, \\n = new line,\r\n# %i and %J = width and height of motion area,\r\n# %K and %L = X and Y coordinates of motion center\r\n# %C = value defined by text_event - do not use with text_event!\r\n# You can put quotation marks around the text to allow\r\n# leading spaces\r\n############################################################\r\n\r\n# Locate and draw a box around the moving object.\r\n# Valid values: on, off and preview (default: off)\r\n# Set to ''preview'' will only draw a box in preview_shot pictures.\r\nlocate on\r\n\r\n# Draws the timestamp using same options as C function strftime(3)\r\n# Default: %Y-%m-%d\\n%T = date in ISO format and time in 24 hour clock\r\n# Text is placed in lower right corner\r\ntext_right %Y-%m-%d\\n%T-%q\r\n\r\n# Draw a user defined text on the images using same options as C function strftime(3)\r\n# Default: Not defined = no text\r\n# Text is placed in lower left corner\r\ntext_left MODULE-JENS\r\n\r\n# Draw the number of changed pixed on the images (default: off)\r\n# Will normally be set to off except when you setup and adjust the motion settings\r\n# Text is placed in upper right corner\r\ntext_changes off\r\n\r\n# This option defines the value of the special event conversion specifier %C\r\n# You can use any conversion specifier in this option except %C. Date and time\r\n# values are from the timestamp of the first image in the current event.\r\n# Default: %Y%m%d%H%M%S\r\n# The idea is that %C can be used filenames and text_left/right for creating\r\n# a unique identifier for each event.\r\ntext_event %Y%m%d%H%M%S\r\n\r\n# Draw characters at twice normal size on images. (default: off)\r\ntext_double on\r\n\r\n\r\n############################################################\r\n# Target Directories and filenames For Images And Films\r\n# For the options snapshot_, jpeg_, mpeg_ and timelapse_filename\r\n# you can use conversion specifiers\r\n# %Y = year, %m = month, %d = date,\r\n# %H = hour, %M = minute, %S = second,\r\n# %v = event, %q = frame number, %t = thread (camera) number,\r\n# %D = changed pixels, %N = noise level,\r\n# %i and %J = width and height of motion area,\r\n# %K and %L = X and Y coordinates of motion center\r\n# %C = value defined by text_event\r\n# Quotation marks round string are allowed.\r\n############################################################\r\n\r\n# Target base directory for pictures and films\r\n# Recommended to use absolute path. (Default: current working directory)\r\ntarget_dir /mnt/nfscontrol/b8:27:eb:d5:dc:f0\r\n#target_dir /dev/null\r\n#target_dir /root/test\r\n\r\n# File path for snapshots (jpeg or ppm) relative to target_dir\r\n# Default: %v-%Y%m%d%H%M%S-snapshot\r\n# Default value is equivalent to legacy oldlayout option\r\n# For Motion 3.0 compatible mode choose: %Y/%m/%d/%H/%M/%S-snapshot\r\n# File extension .jpg or .ppm is automatically added so do not include this.\r\n# Note: A symbolic link called lastsnap.jpg created in the target_dir will always\r\n# point to the latest snapshot, unless snapshot_filename is exactly ''lastsnap''\r\nsnapshot_filename %v-%Y%m%d%H%M%S-snapshot\r\n\r\n# File path for motion triggered images (jpeg or ppm) relative to target_dir\r\n# Default: %v-%Y%m%d%H%M%S-%q\r\n# Default value is equivalent to legacy oldlayout option\r\n# For Motion 3.0 compatible mode choose: %Y/%m/%d/%H/%M/%S-%q\r\n# File extension .jpg or .ppm is automatically added so do not include this\r\n# Set to ''preview'' together with best-preview feature enables special naming\r\n# convention for preview shots. See motion guide for details\r\njpeg_filename %v-%Y%m%d%H%M%S-%q\r\n\r\n# File path for motion triggered ffmpeg films (mpeg) relative to target_dir\r\n# Default: %v-%Y%m%d%H%M%S\r\n# Default value is equivalent to legacy oldlayout option\r\n# For Motion 3.0 compatible mode choose: %Y/%m/%d/%H%M%S\r\n# File extension .mpg or .avi is automatically added so do not include this\r\n# This option was previously called ffmpeg_filename\r\nmovie_filename %v-%Y%m%d%H%M%S\r\n\r\n# File path for timelapse mpegs relative to target_dir\r\n# Default: %Y%m%d-timelapse\r\n# Default value is near equivalent to legacy oldlayout option\r\n# For Motion 3.0 compatible mode choose: %Y/%m/%d-timelapse\r\n# File extension .mpg is automatically added so do not include this\r\ntimelapse_filename %Y%m%d-timelapse\r\n\r\n\r\n############################################################\r\n# Live Webcam Server\r\n############################################################\r\n\r\n# The mini-http server listens to this port for requests (default: 0 = disabled)\r\nwebcam_port 1027\r\n\r\n# Quality of the jpeg (in percent) images produced (default: 50) \r\nwebcam_quality 60\r\n\r\n# Output frames at 1 fps when no motion is detected and increase to the\r\n# rate given by webcam_maxrate when motion is detected (default: off)\r\nwebcam_motion off\r\n\r\n# Maximum framerate for webcam streams (default: 1)\r\nwebcam_maxrate 30\r\n\r\n# Restrict webcam connections to localhost only (default: on)\r\nwebcam_localhost off\r\n\r\n# Limits the number of images per connection (default: 0 = unlimited)\r\n# Number can be defined by multiplying actual webcam rate by desired number of seconds\r\n# Actual webcam rate is the smallest of the numbers framerate and webcam_maxrate\r\nwebcam_limit 0\r\n\r\n\r\n############################################################\r\n# HTTP Based Control\r\n############################################################\r\n\r\n# TCP/IP port for the http server to listen on (default: 0 = disabled)\r\ncontrol_port 8080\r\n\r\n# Restrict control connections to localhost only (default: on)\r\ncontrol_localhost off\r\n\r\n# Output for http server, select off to choose raw text plain (default: on)\r\ncontrol_html_output on\r\n\r\n# Authentication for the http based control. Syntax username:password\r\n# Default: not defined (Disabled)\r\n; control_authentication username:password\r\n\r\n\r\n############################################################\r\n# Tracking (Pan/Tilt)\r\n############################################################\r\n\r\n# Type of tracker (0=none (default), 1=stepper, 2=iomojo, 3=pwc, 4=generic, 5=uvcvideo)\r\n# The generic type enables the definition of motion center and motion size to\r\n# be used with the conversion specifiers for options like on_motion_detected\r\ntrack_type 0\r\n\r\n# Enable auto tracking (default: off)\r\ntrack_auto off\r\n\r\n# Serial port of motor (default: none)\r\n; track_port value\r\n\r\n# Motor number for x-axis (default: 0)\r\ntrack_motorx 0\r\n\r\n# Motor number for y-axis (default: 0)\r\ntrack_motory 0\r\n\r\n# Maximum value on x-axis (default: 0)\r\ntrack_maxx 0\r\n\r\n# Maximum value on y-axis (default: 0)\r\ntrack_maxy 0\r\n\r\n# ID of an iomojo camera if used (default: 0)\r\ntrack_iomojo_id 0\r\n\r\n# Angle in degrees the camera moves per step on the X-axis\r\n# with auto-track (default: 10)\r\n# Currently only used with pwc type cameras\r\ntrack_step_angle_x 10\r\n\r\n# Angle in degrees the camera moves per step on the Y-axis\r\n# with auto-track (default: 10)\r\n# Currently only used with pwc type cameras\r\ntrack_step_angle_y 10\r\n\r\n# Delay to wait for after tracking movement as number\r\n# of picture frames (default: 10)\r\ntrack_move_wait 10\r\n\r\n# Speed to set the motor to (stepper motor option) (default: 255)\r\ntrack_speed 255\r\n\r\n# Number of steps to make (stepper motor option) (default: 40)\r\ntrack_stepsize 40\r\n\r\n\r\n############################################################\r\n# External Commands, Warnings and Logging:\r\n# You can use conversion specifiers for the on_xxxx commands\r\n# %Y = year, %m = month, %d = date,\r\n# %H = hour, %M = minute, %S = second,\r\n# %v = event, %q = frame number, %t = thread (camera) number,\r\n# %D = changed pixels, %N = noise level,\r\n# %i and %J = width and height of motion area,\r\n# %K and %L = X and Y coordinates of motion center\r\n# %C = value defined by text_event\r\n# %f = filename with full path\r\n# %n = number indicating filetype\r\n# Both %f and %n are only defined for on_picture_save,\r\n# on_movie_start and on_movie_end\r\n# Quotation marks round string are allowed.\r\n############################################################\r\n\r\n# Do not sound beeps when detecting motion (default: on)\r\n# Note: Motion never beeps when running in daemon mode.\r\nquiet on\r\n\r\n# Command to be executed when an event starts. (default: none)\r\n# An event starts at first motion detected after a period of no motion defined by gap \r\n; on_event_start value\r\n\r\n# Command to be executed when an event ends after a period of no motion\r\n# (default: none). The period of no motion is defined by option gap.\r\n; on_event_end value\r\n\r\n# Command to be executed when a picture (.ppm|.jpg) is saved (default: none)\r\n# To give the filename as an argument to a command append it with %f\r\n; on_picture_save value\r\n\r\n# Command to be executed when a motion frame is detected (default: none)\r\n; on_motion_detected value\r\n\r\n# Command to be executed when motion in a predefined area is detected\r\n# Check option ''area_detect''.   (default: none)\r\n; on_area_detected value\r\n\r\n# Command to be executed when a movie file (.mpg|.avi) is created. (default: none)\r\n# To give the filename as an argument to a command append it with %f\r\n; on_movie_start value\r\n\r\n# Command to be executed when a movie file (.mpg|.avi) is closed. (default: none)\r\n# To give the filename as an argument to a command append it with %f\r\n; on_movie_end value\r\n#on_movie_end /root/create_video_link.sh %f\r\n\r\n# Command to be executed when a camera can''t be opened or if it is lost\r\n# NOTE: There is situations when motion doesn''t detect a lost camera!\r\n# It depends on the driver, some drivers don''t detect a lost camera at all\r\n# Some hang the motion thread. Some even hang the PC! (default: none)\r\n; on_camera_lost value\r\n\r\n############################################################\r\n# Common Options For MySQL and PostgreSQL database features.\r\n# Options require the MySQL/PostgreSQL options to be active also.\r\n############################################################\r\n\r\n# Log to the database when creating motion triggered image file  (default: on)\r\nsql_log_image on\r\n\r\n# Log to the database when creating a snapshot image file (default: on)\r\nsql_log_snapshot on\r\n\r\n# Log to the database when creating motion triggered mpeg file (default: off)\r\nsql_log_mpeg off\r\n\r\n# Log to the database when creating timelapse mpeg file (default: off)\r\nsql_log_timelapse off\r\n\r\n# SQL query string that is sent to the database\r\n# Use same conversion specifiers has for text features\r\n# Additional special conversion specifiers are\r\n# %n = the number representing the file_type\r\n# %f = filename with full path\r\n# Default value:\r\n# insert into security(camera, filename, frame, file_type, time_stamp, text_event) values(''%t'', ''%f'', ''%q'', ''%n'', ''%Y-%m-%d %T'', ''%C'')\r\nsql_query insert into security(camera, filename, frame, file_type, time_stamp, event_time_stamp) values(''%t'', ''%f'', ''%q'', ''%n'', ''%Y-%m-%d %T'', ''%C'')\r\n\r\n\r\n############################################################\r\n# Database Options For MySQL\r\n############################################################\r\n\r\n# Mysql database to log to (default: not defined)\r\n; mysql_db value\r\n\r\n# The host on which the database is located (default: localhost)\r\n; mysql_host value\r\n\r\n# User account name for MySQL database (default: not defined)\r\n; mysql_user value\r\n\r\n# User password for MySQL database (default: not defined)\r\n; mysql_password value\r\n\r\n\r\n############################################################\r\n# Database Options For PostgreSQL\r\n############################################################\r\n\r\n# PostgreSQL database to log to (default: not defined)\r\n; pgsql_db value\r\n\r\n# The host on which the database is located (default: localhost)\r\n; pgsql_host value\r\n\r\n# User account name for PostgreSQL database (default: not defined)\r\n; pgsql_user value\r\n\r\n# User password for PostgreSQL database (default: not defined)\r\n; pgsql_password value\r\n\r\n# Port on which the PostgreSQL database is located (default: 5432)\r\n; pgsql_port 5432\r\n\r\n\r\n############################################################\r\n# Video Loopback Device (vloopback project)\r\n############################################################\r\n\r\n# Output images to a video4linux loopback device\r\n# The value ''-'' means next available (default: not defined)\r\n; video_pipe value\r\n\r\n# Output motion images to a video4linux loopback device\r\n# The value ''-'' means next available (default: not defined)\r\n; motion_video_pipe value\r\n\r\n\r\n##############################################################\r\n# Thread config files - One for each camera.\r\n# Except if only one camera - You only need this config file.\r\n# If you have more than one camera you MUST define one thread\r\n# config file for each camera in addition to this config file.\r\n##############################################################\r\n\r\n# Remember: If you have more than one camera you must have one\r\n# thread file for each camera. E.g. 2 cameras requires 3 files:\r\n# This motion.conf file AND thread1.conf and thread2.conf.\r\n# Only put the options that are unique to each camera in the\r\n# thread config files. \r\n; thread /usr/local/etc/thread1.conf\r\n; thread /usr/local/etc/thread2.conf\r\n; thread /usr/local/etc/thread3.conf\r\n; thread /usr/local/etc/thread4.conf\r\n\r\n'),
('b8:27:eb:d5:dc:f0', 'RC.LOCAL', '/etc/rc.local', '#!/bin/sh -e\r\n#\r\n# rc.local\r\n#\r\n\r\n_IP=$(hostname -I) || true\r\nif [ "$_IP" ]; then\r\n  printf "My IP address is %s\\n" "$_IP"\r\nfi\r\n\r\nprintf "\\n*********************************\\n---------------------------------\\nExecuting the configuration receiver.\\n\\n"\r\nphp -q /root/startup/1-start.php\r\nphp -q /root/startup/2-configure.php\r\n\r\necho "Initializing BCM" >> /root/startup/log.txt\r\n/root/files/jens/init \r\n\r\necho "Starting motion" >> /root/startup/log.txt\r\nmotion &\r\n\r\nexit 0');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `tbl_minfo`
--

CREATE TABLE IF NOT EXISTS `tbl_minfo` (
  `MAC` varchar(17) NOT NULL,
  `NAME` varchar(64) NOT NULL,
  `DESC` varchar(256) NOT NULL,
  `TYPE` varchar(512) NOT NULL,
  PRIMARY KEY (`MAC`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Gegevens worden uitgevoerd voor tabel `tbl_minfo`
--

INSERT INTO `tbl_minfo` (`MAC`, `NAME`, `DESC`, `TYPE`) VALUES
('b8:27:eb:0f:05:c4', 'Debug module Wesley', 'Deze module wordt gebruikt om de laatste nieuwe code te testen.', 'T-L-Sensor'),
('b8:27:eb:9d:e6:3a', 'Jelleeuh', 'Module van Jelle', 'Camera'),
('b8:27:eb:d5:dc:f0', 'Camera Jens', 'Deze camera staat in de centrale.', 'Camera+T-L-Sensor');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `tbl_modules`
--

CREATE TABLE IF NOT EXISTS `tbl_modules` (
  `MAC` varchar(17) NOT NULL,
  `IP` varchar(15) NOT NULL,
  `HOSTNAME` text NOT NULL,
  `status` int(1) NOT NULL,
  `uptime` int(11) NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`MAC`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Gegevens worden uitgevoerd voor tabel `tbl_modules`
--

INSERT INTO `tbl_modules` (`MAC`, `IP`, `HOSTNAME`, `status`, `uptime`, `last_update`) VALUES
('b8:27:eb:0f:05:c4', '10.0.3.228', 'module-wesley1', 0, 228, '2015-04-23 20:45:05'),
('b8:27:eb:9d:e6:3a', '172.16.0.190', 'module-jelle', 0, 6, '2015-03-23 18:30:45'),
('b8:27:eb:d5:dc:f0', '10.0.3.238', 'module-jens', 0, 38379, '2015-04-21 21:57:01');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `tbl_sensordata`
--

CREATE TABLE IF NOT EXISTS `tbl_sensordata` (
  `sdata_id` int(11) NOT NULL AUTO_INCREMENT,
  `sdata_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MAC` varchar(17) NOT NULL,
  `sensor_type` varchar(30) NOT NULL,
  `value` int(10) NOT NULL,
  PRIMARY KEY (`sdata_id`,`sdata_time`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=443 ;

--
-- Gegevens worden uitgevoerd voor tabel `tbl_sensordata`
--

INSERT INTO `tbl_sensordata` (`sdata_id`, `sdata_time`, `MAC`, `sensor_type`, `value`) VALUES
(55, '2015-04-23 17:32:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(56, '2015-04-23 17:32:06', 'b8:27:eb:0f:05:c4', 'light', 761),
(57, '2015-04-23 17:33:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(58, '2015-04-23 17:33:03', 'b8:27:eb:0f:05:c4', 'light', 756),
(59, '2015-04-23 17:34:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(60, '2015-04-23 17:34:05', 'b8:27:eb:0f:05:c4', 'light', 747),
(61, '2015-04-23 17:35:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(62, '2015-04-23 17:35:03', 'b8:27:eb:0f:05:c4', 'light', 507),
(63, '2015-04-23 17:36:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(64, '2015-04-23 17:36:05', 'b8:27:eb:0f:05:c4', 'light', 516),
(65, '2015-04-23 17:37:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(66, '2015-04-23 17:37:03', 'b8:27:eb:0f:05:c4', 'light', 524),
(67, '2015-04-23 17:38:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(68, '2015-04-23 17:38:06', 'b8:27:eb:0f:05:c4', 'light', 479),
(69, '2015-04-23 17:39:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(70, '2015-04-23 17:39:03', 'b8:27:eb:0f:05:c4', 'light', 463),
(71, '2015-04-23 17:40:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(72, '2015-04-23 17:40:05', 'b8:27:eb:0f:05:c4', 'light', 454),
(73, '2015-04-23 17:41:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(74, '2015-04-23 17:41:02', 'b8:27:eb:0f:05:c4', 'light', 465),
(75, '2015-04-23 17:42:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(76, '2015-04-23 17:42:06', 'b8:27:eb:0f:05:c4', 'light', 445),
(77, '2015-04-23 17:43:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(78, '2015-04-23 17:43:02', 'b8:27:eb:0f:05:c4', 'light', 444),
(79, '2015-04-23 17:44:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(80, '2015-04-23 17:44:06', 'b8:27:eb:0f:05:c4', 'light', 444),
(81, '2015-04-23 17:45:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(82, '2015-04-23 17:45:03', 'b8:27:eb:0f:05:c4', 'light', 439),
(83, '2015-04-23 17:46:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(84, '2015-04-23 17:46:05', 'b8:27:eb:0f:05:c4', 'light', 433),
(85, '2015-04-23 17:47:03', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(86, '2015-04-23 17:47:03', 'b8:27:eb:0f:05:c4', 'light', 446),
(87, '2015-04-23 17:48:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(88, '2015-04-23 17:48:05', 'b8:27:eb:0f:05:c4', 'light', 425),
(89, '2015-04-23 17:49:03', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(90, '2015-04-23 17:49:03', 'b8:27:eb:0f:05:c4', 'light', 417),
(91, '2015-04-23 17:50:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(92, '2015-04-23 17:50:05', 'b8:27:eb:0f:05:c4', 'light', 405),
(93, '2015-04-23 17:51:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(94, '2015-04-23 17:51:02', 'b8:27:eb:0f:05:c4', 'light', 404),
(95, '2015-04-23 17:52:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(96, '2015-04-23 17:52:06', 'b8:27:eb:0f:05:c4', 'light', 401),
(97, '2015-04-23 17:53:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(98, '2015-04-23 17:53:02', 'b8:27:eb:0f:05:c4', 'light', 401),
(99, '2015-04-23 17:54:06', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(100, '2015-04-23 17:54:06', 'b8:27:eb:0f:05:c4', 'light', 400),
(101, '2015-04-23 17:55:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(102, '2015-04-23 17:55:03', 'b8:27:eb:0f:05:c4', 'light', 392),
(103, '2015-04-23 17:56:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(104, '2015-04-23 17:56:05', 'b8:27:eb:0f:05:c4', 'light', 384),
(105, '2015-04-23 17:57:03', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(106, '2015-04-23 17:57:03', 'b8:27:eb:0f:05:c4', 'light', 379),
(107, '2015-04-23 17:58:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(108, '2015-04-23 17:58:05', 'b8:27:eb:0f:05:c4', 'light', 364),
(109, '2015-04-23 17:59:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(110, '2015-04-23 17:59:02', 'b8:27:eb:0f:05:c4', 'light', 358),
(111, '2015-04-23 18:00:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(112, '2015-04-23 18:00:06', 'b8:27:eb:0f:05:c4', 'light', 365),
(113, '2015-04-23 18:01:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(114, '2015-04-23 18:01:02', 'b8:27:eb:0f:05:c4', 'light', 352),
(115, '2015-04-23 18:02:06', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(116, '2015-04-23 18:02:06', 'b8:27:eb:0f:05:c4', 'light', 345),
(117, '2015-04-23 18:03:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(118, '2015-04-23 18:03:02', 'b8:27:eb:0f:05:c4', 'light', 344),
(119, '2015-04-23 18:04:06', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(120, '2015-04-23 18:04:06', 'b8:27:eb:0f:05:c4', 'light', 336),
(121, '2015-04-23 18:05:03', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(122, '2015-04-23 18:05:03', 'b8:27:eb:0f:05:c4', 'light', 341),
(123, '2015-04-23 18:06:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(124, '2015-04-23 18:06:05', 'b8:27:eb:0f:05:c4', 'light', 321),
(125, '2015-04-23 18:07:03', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(126, '2015-04-23 18:07:03', 'b8:27:eb:0f:05:c4', 'light', 315),
(127, '2015-04-23 18:08:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(128, '2015-04-23 18:08:05', 'b8:27:eb:0f:05:c4', 'light', 293),
(129, '2015-04-23 18:09:03', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(130, '2015-04-23 18:09:03', 'b8:27:eb:0f:05:c4', 'light', 290),
(131, '2015-04-23 18:10:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(132, '2015-04-23 18:10:05', 'b8:27:eb:0f:05:c4', 'light', 282),
(133, '2015-04-23 18:11:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(134, '2015-04-23 18:11:02', 'b8:27:eb:0f:05:c4', 'light', 453),
(135, '2015-04-23 18:12:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(136, '2015-04-23 18:12:06', 'b8:27:eb:0f:05:c4', 'light', 437),
(137, '2015-04-23 18:13:02', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(138, '2015-04-23 18:13:03', 'b8:27:eb:0f:05:c4', 'light', 421),
(139, '2015-04-23 18:14:06', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(140, '2015-04-23 18:14:06', 'b8:27:eb:0f:05:c4', 'light', 425),
(141, '2015-04-23 18:15:03', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(142, '2015-04-23 18:15:03', 'b8:27:eb:0f:05:c4', 'light', 407),
(143, '2015-04-23 18:16:05', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(144, '2015-04-23 18:16:05', 'b8:27:eb:0f:05:c4', 'light', 277),
(145, '2015-04-23 18:17:03', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(146, '2015-04-23 18:17:03', 'b8:27:eb:0f:05:c4', 'light', 264),
(147, '2015-04-23 18:18:05', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(148, '2015-04-23 18:18:06', 'b8:27:eb:0f:05:c4', 'light', 258),
(149, '2015-04-23 18:19:02', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(150, '2015-04-23 18:19:02', 'b8:27:eb:0f:05:c4', 'light', 252),
(151, '2015-04-23 18:20:06', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(152, '2015-04-23 18:20:06', 'b8:27:eb:0f:05:c4', 'light', 243),
(153, '2015-04-23 18:21:02', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(154, '2015-04-23 18:21:02', 'b8:27:eb:0f:05:c4', 'light', 233),
(155, '2015-04-23 18:22:06', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(156, '2015-04-23 18:22:06', 'b8:27:eb:0f:05:c4', 'light', 222),
(157, '2015-04-23 18:23:03', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(158, '2015-04-23 18:23:03', 'b8:27:eb:0f:05:c4', 'light', 211),
(159, '2015-04-23 18:24:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(160, '2015-04-23 18:24:05', 'b8:27:eb:0f:05:c4', 'light', 202),
(161, '2015-04-23 18:25:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(162, '2015-04-23 18:25:03', 'b8:27:eb:0f:05:c4', 'light', 203),
(163, '2015-04-23 18:26:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(164, '2015-04-23 18:26:06', 'b8:27:eb:0f:05:c4', 'light', 195),
(165, '2015-04-23 18:27:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(166, '2015-04-23 18:27:02', 'b8:27:eb:0f:05:c4', 'light', 185),
(167, '2015-04-23 18:28:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(168, '2015-04-23 18:28:06', 'b8:27:eb:0f:05:c4', 'light', 177),
(169, '2015-04-23 18:29:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(170, '2015-04-23 18:29:03', 'b8:27:eb:0f:05:c4', 'light', 169),
(171, '2015-04-23 18:30:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(172, '2015-04-23 18:30:05', 'b8:27:eb:0f:05:c4', 'light', 158),
(173, '2015-04-23 18:31:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(174, '2015-04-23 18:31:03', 'b8:27:eb:0f:05:c4', 'light', 146),
(175, '2015-04-23 18:32:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(176, '2015-04-23 18:32:05', 'b8:27:eb:0f:05:c4', 'light', 138),
(177, '2015-04-23 18:33:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(178, '2015-04-23 18:33:03', 'b8:27:eb:0f:05:c4', 'light', 131),
(179, '2015-04-23 18:34:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(180, '2015-04-23 18:34:06', 'b8:27:eb:0f:05:c4', 'light', 122),
(181, '2015-04-23 18:35:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(182, '2015-04-23 18:35:02', 'b8:27:eb:0f:05:c4', 'light', 122),
(183, '2015-04-23 18:36:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(184, '2015-04-23 18:36:06', 'b8:27:eb:0f:05:c4', 'light', 114),
(185, '2015-04-23 18:37:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(186, '2015-04-23 18:37:03', 'b8:27:eb:0f:05:c4', 'light', 106),
(187, '2015-04-23 18:38:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(188, '2015-04-23 18:38:06', 'b8:27:eb:0f:05:c4', 'light', 98),
(189, '2015-04-23 18:39:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(190, '2015-04-23 18:39:04', 'b8:27:eb:0f:05:c4', 'light', 91),
(191, '2015-04-23 18:40:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(192, '2015-04-23 18:40:06', 'b8:27:eb:0f:05:c4', 'light', 84),
(193, '2015-04-23 18:41:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(194, '2015-04-23 18:41:03', 'b8:27:eb:0f:05:c4', 'light', 78),
(195, '2015-04-23 18:42:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(196, '2015-04-23 18:42:05', 'b8:27:eb:0f:05:c4', 'light', 73),
(197, '2015-04-23 18:43:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(198, '2015-04-23 18:43:03', 'b8:27:eb:0f:05:c4', 'light', 67),
(199, '2015-04-23 18:44:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(200, '2015-04-23 18:44:05', 'b8:27:eb:0f:05:c4', 'light', 63),
(201, '2015-04-23 18:45:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(202, '2015-04-23 18:45:02', 'b8:27:eb:0f:05:c4', 'light', 58),
(203, '2015-04-23 18:46:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(204, '2015-04-23 18:46:06', 'b8:27:eb:0f:05:c4', 'light', 54),
(205, '2015-04-23 18:47:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(206, '2015-04-23 18:47:02', 'b8:27:eb:0f:05:c4', 'light', 51),
(207, '2015-04-23 18:48:06', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(208, '2015-04-23 18:48:06', 'b8:27:eb:0f:05:c4', 'light', 48),
(209, '2015-04-23 18:49:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(210, '2015-04-23 18:49:03', 'b8:27:eb:0f:05:c4', 'light', 41),
(211, '2015-04-23 18:50:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(212, '2015-04-23 18:50:05', 'b8:27:eb:0f:05:c4', 'light', 39),
(213, '2015-04-23 18:51:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(214, '2015-04-23 18:51:03', 'b8:27:eb:0f:05:c4', 'light', 37),
(215, '2015-04-23 18:52:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(216, '2015-04-23 18:52:05', 'b8:27:eb:0f:05:c4', 'light', 33),
(217, '2015-04-23 18:53:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(218, '2015-04-23 18:53:02', 'b8:27:eb:0f:05:c4', 'light', 30),
(219, '2015-04-23 18:54:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(220, '2015-04-23 18:54:06', 'b8:27:eb:0f:05:c4', 'light', 27),
(221, '2015-04-23 18:55:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(222, '2015-04-23 18:55:02', 'b8:27:eb:0f:05:c4', 'light', 25),
(223, '2015-04-23 18:56:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(224, '2015-04-23 18:56:06', 'b8:27:eb:0f:05:c4', 'light', 22),
(225, '2015-04-23 18:57:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(226, '2015-04-23 18:57:03', 'b8:27:eb:0f:05:c4', 'light', 22),
(227, '2015-04-23 18:58:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(228, '2015-04-23 18:58:05', 'b8:27:eb:0f:05:c4', 'light', 22),
(229, '2015-04-23 18:59:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(230, '2015-04-23 18:59:03', 'b8:27:eb:0f:05:c4', 'light', 19),
(231, '2015-04-23 19:00:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(232, '2015-04-23 19:00:05', 'b8:27:eb:0f:05:c4', 'light', 18),
(233, '2015-04-23 19:01:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(234, '2015-04-23 19:01:02', 'b8:27:eb:0f:05:c4', 'light', 17),
(235, '2015-04-23 19:02:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(236, '2015-04-23 19:02:06', 'b8:27:eb:0f:05:c4', 'light', 17),
(237, '2015-04-23 19:03:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(238, '2015-04-23 19:03:02', 'b8:27:eb:0f:05:c4', 'light', 13),
(239, '2015-04-23 19:04:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(240, '2015-04-23 19:04:06', 'b8:27:eb:0f:05:c4', 'light', 9),
(241, '2015-04-23 19:05:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(242, '2015-04-23 19:05:03', 'b8:27:eb:0f:05:c4', 'light', 9),
(243, '2015-04-23 19:06:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(244, '2015-04-23 19:06:05', 'b8:27:eb:0f:05:c4', 'light', 12),
(245, '2015-04-23 19:07:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(246, '2015-04-23 19:07:03', 'b8:27:eb:0f:05:c4', 'light', 11),
(247, '2015-04-23 19:08:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(248, '2015-04-23 19:08:06', 'b8:27:eb:0f:05:c4', 'light', 10),
(249, '2015-04-23 19:09:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(250, '2015-04-23 19:09:03', 'b8:27:eb:0f:05:c4', 'light', 9),
(251, '2015-04-23 19:10:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(252, '2015-04-23 19:10:06', 'b8:27:eb:0f:05:c4', 'light', 8),
(253, '2015-04-23 19:11:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(254, '2015-04-23 19:11:02', 'b8:27:eb:0f:05:c4', 'light', 8),
(255, '2015-04-23 19:12:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(256, '2015-04-23 19:12:06', 'b8:27:eb:0f:05:c4', 'light', 8),
(257, '2015-04-23 19:13:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(258, '2015-04-23 19:13:03', 'b8:27:eb:0f:05:c4', 'light', 7),
(259, '2015-04-23 19:14:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(260, '2015-04-23 19:14:05', 'b8:27:eb:0f:05:c4', 'light', 8),
(261, '2015-04-23 19:15:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(262, '2015-04-23 19:15:03', 'b8:27:eb:0f:05:c4', 'light', 7),
(263, '2015-04-23 19:16:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(264, '2015-04-23 19:16:05', 'b8:27:eb:0f:05:c4', 'light', 9),
(265, '2015-04-23 19:17:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(266, '2015-04-23 19:17:03', 'b8:27:eb:0f:05:c4', 'light', 10),
(267, '2015-04-23 19:18:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(268, '2015-04-23 19:18:06', 'b8:27:eb:0f:05:c4', 'light', 7),
(269, '2015-04-23 19:19:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(270, '2015-04-23 19:19:02', 'b8:27:eb:0f:05:c4', 'light', 9),
(271, '2015-04-23 19:20:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(272, '2015-04-23 19:20:06', 'b8:27:eb:0f:05:c4', 'light', 7),
(273, '2015-04-23 19:21:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(274, '2015-04-23 19:21:03', 'b8:27:eb:0f:05:c4', 'light', 6),
(275, '2015-04-23 19:22:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(276, '2015-04-23 19:22:06', 'b8:27:eb:0f:05:c4', 'light', 5),
(277, '2015-04-23 19:23:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(278, '2015-04-23 19:23:03', 'b8:27:eb:0f:05:c4', 'light', 7),
(279, '2015-04-23 19:24:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(280, '2015-04-23 19:24:05', 'b8:27:eb:0f:05:c4', 'light', 6),
(281, '2015-04-23 19:25:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(282, '2015-04-23 19:25:03', 'b8:27:eb:0f:05:c4', 'light', 51),
(283, '2015-04-23 19:26:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(284, '2015-04-23 19:26:05', 'b8:27:eb:0f:05:c4', 'light', 47),
(285, '2015-04-23 19:27:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(286, '2015-04-23 19:27:02', 'b8:27:eb:0f:05:c4', 'light', 49),
(287, '2015-04-23 19:28:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(288, '2015-04-23 19:28:06', 'b8:27:eb:0f:05:c4', 'light', 50),
(289, '2015-04-23 19:29:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(290, '2015-04-23 19:29:02', 'b8:27:eb:0f:05:c4', 'light', 50),
(291, '2015-04-23 19:30:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(292, '2015-04-23 19:30:06', 'b8:27:eb:0f:05:c4', 'light', 50),
(293, '2015-04-23 19:31:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(294, '2015-04-23 19:31:03', 'b8:27:eb:0f:05:c4', 'light', 50),
(295, '2015-04-23 19:32:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(296, '2015-04-23 19:32:05', 'b8:27:eb:0f:05:c4', 'light', 47),
(297, '2015-04-23 19:33:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(298, '2015-04-23 19:33:03', 'b8:27:eb:0f:05:c4', 'light', 46),
(299, '2015-04-23 19:34:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(300, '2015-04-23 19:34:05', 'b8:27:eb:0f:05:c4', 'light', 54),
(301, '2015-04-23 19:35:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(302, '2015-04-23 19:35:02', 'b8:27:eb:0f:05:c4', 'light', 55),
(303, '2015-04-23 19:36:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(304, '2015-04-23 19:36:06', 'b8:27:eb:0f:05:c4', 'light', 55),
(305, '2015-04-23 19:37:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(306, '2015-04-23 19:37:02', 'b8:27:eb:0f:05:c4', 'light', 56),
(307, '2015-04-23 19:38:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(308, '2015-04-23 19:38:06', 'b8:27:eb:0f:05:c4', 'light', 55),
(309, '2015-04-23 19:39:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(310, '2015-04-23 19:39:03', 'b8:27:eb:0f:05:c4', 'light', 53),
(311, '2015-04-23 19:40:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(312, '2015-04-23 19:40:06', 'b8:27:eb:0f:05:c4', 'light', 52),
(313, '2015-04-23 19:41:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(314, '2015-04-23 19:41:03', 'b8:27:eb:0f:05:c4', 'light', 52),
(315, '2015-04-23 19:42:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(316, '2015-04-23 19:42:05', 'b8:27:eb:0f:05:c4', 'light', 52),
(317, '2015-04-23 19:43:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(318, '2015-04-23 19:43:03', 'b8:27:eb:0f:05:c4', 'light', 58),
(319, '2015-04-23 19:44:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(320, '2015-04-23 19:44:05', 'b8:27:eb:0f:05:c4', 'light', 59),
(321, '2015-04-23 19:45:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(322, '2015-04-23 19:45:02', 'b8:27:eb:0f:05:c4', 'light', 58),
(323, '2015-04-23 19:46:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(324, '2015-04-23 19:46:06', 'b8:27:eb:0f:05:c4', 'light', 58),
(325, '2015-04-23 19:47:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(326, '2015-04-23 19:47:02', 'b8:27:eb:0f:05:c4', 'light', 59),
(327, '2015-04-23 19:48:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(328, '2015-04-23 19:48:06', 'b8:27:eb:0f:05:c4', 'light', 59),
(329, '2015-04-23 19:49:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(330, '2015-04-23 19:49:02', 'b8:27:eb:0f:05:c4', 'light', 59),
(331, '2015-04-23 19:50:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(332, '2015-04-23 19:50:06', 'b8:27:eb:0f:05:c4', 'light', 59),
(333, '2015-04-23 19:51:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(334, '2015-04-23 19:51:03', 'b8:27:eb:0f:05:c4', 'light', 63),
(335, '2015-04-23 19:52:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(336, '2015-04-23 19:52:05', 'b8:27:eb:0f:05:c4', 'light', 34),
(337, '2015-04-23 19:53:03', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(338, '2015-04-23 19:53:03', 'b8:27:eb:0f:05:c4', 'light', 28),
(339, '2015-04-23 19:54:05', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(340, '2015-04-23 19:54:05', 'b8:27:eb:0f:05:c4', 'light', 29),
(341, '2015-04-23 19:55:02', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(342, '2015-04-23 19:55:02', 'b8:27:eb:0f:05:c4', 'light', 30),
(343, '2015-04-23 19:56:05', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(344, '2015-04-23 19:56:06', 'b8:27:eb:0f:05:c4', 'light', 27),
(345, '2015-04-23 19:57:02', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(346, '2015-04-23 19:57:02', 'b8:27:eb:0f:05:c4', 'light', 30),
(347, '2015-04-23 19:58:06', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(348, '2015-04-23 19:58:06', 'b8:27:eb:0f:05:c4', 'light', 34),
(349, '2015-04-23 19:59:02', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(350, '2015-04-23 19:59:03', 'b8:27:eb:0f:05:c4', 'light', 33),
(351, '2015-04-23 20:00:05', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(352, '2015-04-23 20:00:05', 'b8:27:eb:0f:05:c4', 'light', 31),
(353, '2015-04-23 20:01:03', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(354, '2015-04-23 20:01:03', 'b8:27:eb:0f:05:c4', 'light', 35),
(355, '2015-04-23 20:02:05', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(356, '2015-04-23 20:02:05', 'b8:27:eb:0f:05:c4', 'light', 34),
(357, '2015-04-23 20:03:03', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(358, '2015-04-23 20:03:03', 'b8:27:eb:0f:05:c4', 'light', 35),
(359, '2015-04-23 20:04:05', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(360, '2015-04-23 20:04:05', 'b8:27:eb:0f:05:c4', 'light', 34),
(361, '2015-04-23 20:05:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(362, '2015-04-23 20:05:02', 'b8:27:eb:0f:05:c4', 'light', 36),
(363, '2015-04-23 20:06:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(364, '2015-04-23 20:06:06', 'b8:27:eb:0f:05:c4', 'light', 35),
(365, '2015-04-23 20:07:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(366, '2015-04-23 20:07:02', 'b8:27:eb:0f:05:c4', 'light', 34),
(367, '2015-04-23 20:08:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(368, '2015-04-23 20:08:06', 'b8:27:eb:0f:05:c4', 'light', 35),
(369, '2015-04-23 20:09:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(370, '2015-04-23 20:09:03', 'b8:27:eb:0f:05:c4', 'light', 34),
(371, '2015-04-23 20:10:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(372, '2015-04-23 20:10:06', 'b8:27:eb:0f:05:c4', 'light', 34),
(373, '2015-04-23 20:11:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(374, '2015-04-23 20:11:02', 'b8:27:eb:0f:05:c4', 'light', 34),
(375, '2015-04-23 20:12:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(376, '2015-04-23 20:12:06', 'b8:27:eb:0f:05:c4', 'light', 28),
(377, '2015-04-23 20:13:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(378, '2015-04-23 20:13:03', 'b8:27:eb:0f:05:c4', 'light', 27),
(379, '2015-04-23 20:14:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(380, '2015-04-23 20:14:05', 'b8:27:eb:0f:05:c4', 'light', 27),
(381, '2015-04-23 20:15:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(382, '2015-04-23 20:15:03', 'b8:27:eb:0f:05:c4', 'light', 26),
(383, '2015-04-23 20:16:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(384, '2015-04-23 20:16:05', 'b8:27:eb:0f:05:c4', 'light', 25),
(385, '2015-04-23 20:17:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(386, '2015-04-23 20:17:02', 'b8:27:eb:0f:05:c4', 'light', 29),
(387, '2015-04-23 20:18:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(388, '2015-04-23 20:18:06', 'b8:27:eb:0f:05:c4', 'light', 27),
(389, '2015-04-23 20:19:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(390, '2015-04-23 20:19:02', 'b8:27:eb:0f:05:c4', 'light', 25),
(391, '2015-04-23 20:20:06', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(392, '2015-04-23 20:20:06', 'b8:27:eb:0f:05:c4', 'light', 31),
(393, '2015-04-23 20:21:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(394, '2015-04-23 20:21:03', 'b8:27:eb:0f:05:c4', 'light', 31),
(395, '2015-04-23 20:22:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(396, '2015-04-23 20:22:05', 'b8:27:eb:0f:05:c4', 'light', 29),
(397, '2015-04-23 20:23:03', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(398, '2015-04-23 20:23:03', 'b8:27:eb:0f:05:c4', 'light', 28),
(399, '2015-04-23 20:24:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(400, '2015-04-23 20:24:05', 'b8:27:eb:0f:05:c4', 'light', 31),
(401, '2015-04-23 20:25:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(402, '2015-04-23 20:25:02', 'b8:27:eb:0f:05:c4', 'light', 31),
(403, '2015-04-23 20:26:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(404, '2015-04-23 20:26:06', 'b8:27:eb:0f:05:c4', 'light', 32),
(405, '2015-04-23 20:27:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(406, '2015-04-23 20:27:02', 'b8:27:eb:0f:05:c4', 'light', 32),
(407, '2015-04-23 20:28:06', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(408, '2015-04-23 20:28:06', 'b8:27:eb:0f:05:c4', 'light', 31),
(409, '2015-04-23 20:29:02', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(410, '2015-04-23 20:29:03', 'b8:27:eb:0f:05:c4', 'light', 30),
(411, '2015-04-23 20:30:05', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(412, '2015-04-23 20:30:05', 'b8:27:eb:0f:05:c4', 'light', 30),
(413, '2015-04-23 20:31:03', 'b8:27:eb:0f:05:c4', 'temperature', 33),
(414, '2015-04-23 20:31:03', 'b8:27:eb:0f:05:c4', 'light', 34),
(415, '2015-04-23 20:32:05', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(416, '2015-04-23 20:32:05', 'b8:27:eb:0f:05:c4', 'light', 35),
(417, '2015-04-23 20:33:02', 'b8:27:eb:0f:05:c4', 'temperature', 32),
(418, '2015-04-23 20:33:02', 'b8:27:eb:0f:05:c4', 'light', 35),
(419, '2015-04-23 20:34:05', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(420, '2015-04-23 20:34:06', 'b8:27:eb:0f:05:c4', 'light', 78),
(421, '2015-04-23 20:35:02', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(422, '2015-04-23 20:35:02', 'b8:27:eb:0f:05:c4', 'light', 97),
(423, '2015-04-23 20:36:06', 'b8:27:eb:0f:05:c4', 'temperature', 31),
(424, '2015-04-23 20:36:06', 'b8:27:eb:0f:05:c4', 'light', 98),
(425, '2015-04-23 20:37:02', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(426, '2015-04-23 20:37:03', 'b8:27:eb:0f:05:c4', 'light', 101),
(427, '2015-04-23 20:38:05', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(428, '2015-04-23 20:38:05', 'b8:27:eb:0f:05:c4', 'light', 102),
(429, '2015-04-23 20:39:03', 'b8:27:eb:0f:05:c4', 'temperature', 30),
(430, '2015-04-23 20:39:04', 'b8:27:eb:0f:05:c4', 'light', 101),
(431, '2015-04-23 20:40:06', 'b8:27:eb:0f:05:c4', 'temperature', 29),
(432, '2015-04-23 20:40:06', 'b8:27:eb:0f:05:c4', 'light', 62),
(433, '2015-04-23 20:41:03', 'b8:27:eb:0f:05:c4', 'temperature', 29),
(434, '2015-04-23 20:41:03', 'b8:27:eb:0f:05:c4', 'light', 101),
(435, '2015-04-23 20:42:05', 'b8:27:eb:0f:05:c4', 'temperature', 29),
(436, '2015-04-23 20:42:05', 'b8:27:eb:0f:05:c4', 'light', 100),
(437, '2015-04-23 20:43:02', 'b8:27:eb:0f:05:c4', 'temperature', 29),
(438, '2015-04-23 20:43:02', 'b8:27:eb:0f:05:c4', 'light', 96),
(439, '2015-04-23 20:44:05', 'b8:27:eb:0f:05:c4', 'temperature', 29),
(440, '2015-04-23 20:44:06', 'b8:27:eb:0f:05:c4', 'light', 99),
(441, '2015-04-23 20:45:02', 'b8:27:eb:0f:05:c4', 'temperature', 29),
(442, '2015-04-23 20:45:02', 'b8:27:eb:0f:05:c4', 'light', 98);

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `tbl_users`
--

CREATE TABLE IF NOT EXISTS `tbl_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uname` varchar(45) NOT NULL,
  `prename` varchar(45) NOT NULL,
  `lastname` varchar(45) NOT NULL,
  `password` text NOT NULL,
  `passwordkey` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

--
-- Gegevens worden uitgevoerd voor tabel `tbl_users`
--

INSERT INTO `tbl_users` (`id`, `uname`, `prename`, `lastname`, `password`, `passwordkey`) VALUES
(1, 'test', 'Jens', 'Sterckx', '21CAplOLEsGLE', '21cdedd99c19e2fe8eac675929ca87f70f2c2a4931649583a211d9b6ef1580cd');

--
-- Beperkingen voor gedumpte tabellen
--

--
-- Beperkingen voor tabel `tbl_minfo`
--
ALTER TABLE `tbl_minfo`
  ADD CONSTRAINT `tbl_minfo_ibfk_1` FOREIGN KEY (`MAC`) REFERENCES `tbl_modules` (`MAC`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
